app:
  config:
    scheduler:
      threads: 5

      task:
        CheckServerStatusTask:
          cron: "*/10 * * * * *"

        ServerDataExtraDataReaderTask:
          cron: "*/15 * * * * *"

    server:
      names: >
        kpoc_zookeeper1,
        kpoc_zookeeper2,
        kpoc_zookeeper3,
        kpoc_broker1,
        kpoc_broker2,
        kpoc_broker3,
        kpoc_broker4,
        kpoc_broker5

      data:
        kpoc_zookeeper1:
          location: network
          type: zookeeper
          host: kpoc_zookeeper1
          port: 2181

        kpoc_zookeeper2:
          location: network
          type: zookeeper
          host: kpoc_zookeeper2
          port: 2181

        kpoc_zookeeper3:
          location: network
          type: zookeeper
          host: kpoc_zookeeper3
          port: 2181

        kpoc_broker1:
          location: network
          type: kafka_broker
          host: kpoc_broker1
          port: 9092

        kpoc_broker2:
          location: network
          type: kafka_broker
          host: kpoc_broker2
          port: 9092

        kpoc_broker3:
          location: network
          type: kafka_broker
          host: kpoc_broker3
          port: 9092

        kpoc_broker4:
          location: network
          type: kafka_broker
          host: kpoc_broker4
          port: 9092

        kpoc_broker5:
          location: network
          type: kafka_broker
          host: kpoc_broker4
          port: 9092
