version: "3.5"
services:

  kpoc_app:
    image: "blacktop/kafka:2.6"
    #image: "java:8"
    restart: "unless-stopped"
    container_name: "kpoc_app"
    entrypoint: ["java", "-jar", "-Dspring.profiles.active=docker", "/app/app.jar"]
    command: ""
    networks:
      - "kpoc_network"
    depends_on:
      - "kpoc_zookeeper1"
      - "kpoc_zookeeper2"
      - "kpoc_zookeeper3"
      - "kpoc_broker1"
      - "kpoc_broker2"
      - "kpoc_broker3"
      - "kpoc_broker4"
      - "kpoc_broker5"
    links:
      - "kpoc_zookeeper1"
      - "kpoc_zookeeper2"
      - "kpoc_zookeeper3"
      - "kpoc_broker1"
      - "kpoc_broker2"
      - "kpoc_broker3"
      - "kpoc_broker4"
      - "kpoc_broker5"
    volumes:
      - "../build/libs/kafka-multicluster-poc-0.0.1-SNAPSHOT.jar:/app/app.jar"
    expose:
      - "8080"
    ports:
      - "8080:8080"
